services:
  db:
    env_file: ".env"
    image: 'postgres:16.4-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - lng_network

  app:
    env_file: ".env"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lng_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`api.learnngrow.ru`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

networks:
  lng_network:
    driver: bridge
