services:
  db:
    env_file: ".env"
    image: 'postgres:16.4-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - lng_network

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - lng_network

networks:
  lng_network:
    driver: bridge

