// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files.sql

package repository

import (
	"context"
)

const getFile = `-- name: GetFile :one
SELECT id, slug, fname, fsize, fdata FROM files
WHERE slug == $1
`

func (q *Queries) GetFile(ctx context.Context, slug string) (File, error) {
	row := q.db.QueryRow(ctx, getFile, slug)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Fname,
		&i.Fsize,
		&i.Fdata,
	)
	return i, err
}

const uploadFile = `-- name: UploadFile :exec
INSERT INTO files (slug, fname, fsize, fdata)
VALUES ($1, $2, $3, $4)
`

type UploadFileParams struct {
	Slug  string
	Fname string
	Fsize int32
	Fdata []byte
}

func (q *Queries) UploadFile(ctx context.Context, arg UploadFileParams) error {
	_, err := q.db.Exec(ctx, uploadFile,
		arg.Slug,
		arg.Fname,
		arg.Fsize,
		arg.Fdata,
	)
	return err
}
