// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lessons.sql

package repository

import (
	"context"
)

const createLesson = `-- name: CreateLesson :one
WITH student AS (
	SELECT id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name, slug
	FROM users AS U
	WHERE U.slug = $1
	LIMIT 1
), teacher AS (
	SELECT user_id, subject_ids, biography, id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name, slug
	FROM
		teachers AS T
		INNER JOIN users AS U ON U.id = T.user_id
	WHERE U.slug = $2
	LIMIT 1
)
INSERT INTO lessons (
	student_id
,	teacher_id
,	timestamp_m
,	teacher_notes
,	homework
) VALUES (
	(SELECT id FROM student)
,	(SELECT id FROM teacher)
,	$3
,	$4
,	$5
)
RETURNING id, student_id, teacher_id, timestamp_m, teacher_notes, homework
`

type CreateLessonParams struct {
	Slug         string
	Slug_2       string
	TimestampM   int32
	TeacherNotes string
	Homework     string
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.Slug,
		arg.Slug_2,
		arg.TimestampM,
		arg.TeacherNotes,
		arg.Homework,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TeacherID,
		&i.TimestampM,
		&i.TeacherNotes,
		&i.Homework,
	)
	return i, err
}

const getLessonsByTeacher = `-- name: GetLessonsByTeacher :many
SELECT l.id, l.student_id, l.teacher_id, l.timestamp_m, l.teacher_notes, l.homework
FROM lessons AS L
INNER JOIN teachers AS T ON L.teacher_id = T.user_id
INNER JOIN users AS U ON T.user_id = U.id
WHERE U.email = $1
`

func (q *Queries) GetLessonsByTeacher(ctx context.Context, email string) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, getLessonsByTeacher, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TeacherID,
			&i.TimestampM,
			&i.TeacherNotes,
			&i.Homework,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
