// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lessons.sql

package repository

import (
	"context"
)

const createLesson = `-- name: CreateLesson :one
WITH student AS (
	SELECT id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name, slug
	FROM users AS U
	WHERE U.slug = $1
	LIMIT 1
), teacher AS (
	SELECT user_id, subject_ids, biography, id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name, slug
	FROM
		teachers AS T
		INNER JOIN users AS U ON U.id = T.user_id
	WHERE U.slug = $2
	LIMIT 1
)
INSERT INTO lessons (
	student_id
,	teacher_id
,	timestamp_m
,	teacher_notes
,	homework
) VALUES (
	(SELECT id FROM student)
,	(SELECT id FROM teacher)
,	$3
,	$4
,	$5
)
RETURNING id, student_id, teacher_id, timestamp_m, teacher_notes, homework
`

type CreateLessonParams struct {
	Slug         string
	Slug_2       string
	TimestampM   int32
	TeacherNotes string
	Homework     string
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.Slug,
		arg.Slug_2,
		arg.TimestampM,
		arg.TeacherNotes,
		arg.Homework,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TeacherID,
		&i.TimestampM,
		&i.TeacherNotes,
		&i.Homework,
	)
	return i, err
}
