// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID    int32
	Title string
}

type ConfigTbl struct {
	MaxFilesize pgtype.Int4
}

type Course struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Price       int32
	Year        pgtype.Int2
	CategoryID  int32
	SubjectID   int32
	Slug        string
}

type CourseReview struct {
	ID         int32
	Rating     int16
	Details    pgtype.Text
	AuthorName string
	CourseID   pgtype.Int4
}

type CoursesTeacher struct {
	CourseID  int32
	TeacherID int32
}

type File struct {
	ID    int32
	Slug  string
	Fname string
	Fsize int32
	Fdata []byte
}

type Lesson struct {
	ID           int32
	StudentID    int32
	TeacherID    int32
	TeacherNotes string
	Homework     string
	Ts           pgtype.Timestamptz
	Classwork    string
	Duration     int16
	FileSlug     pgtype.Text
}

type SchoolReview struct {
	ID         int32
	Details    string
	AuthorName string
}

type Subject struct {
	ID    int32
	Title string
}

type Teacher struct {
	UserID     int32
	SubjectIds []int32
	Biography  pgtype.Text
}

type TeacherReview struct {
	ID         int32
	Rating     int16
	Details    pgtype.Text
	AuthorName string
	TeacherID  pgtype.Int4
}

type User struct {
	ID          int32
	Email       string
	Password    []byte
	IsTeacher   pgtype.Bool
	IsSuperuser pgtype.Bool
	FirstName   string
	MiddleName  pgtype.Text
	LastName    string
	Slug        string
	TgChatID    string
}
