// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reviews.sql

package repository

import (
	"context"
)

const createReview = `-- name: CreateReview :one
INSERT INTO school_reviews (details, author_name)
	VALUES ($1, $2)
RETURNING id, details, author_name
`

type CreateReviewParams struct {
	Details    string
	AuthorName string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (SchoolReview, error) {
	row := q.db.QueryRow(ctx, createReview, arg.Details, arg.AuthorName)
	var i SchoolReview
	err := row.Scan(&i.ID, &i.Details, &i.AuthorName)
	return i, err
}
