// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: students.sql

package repository

import (
	"context"
)

const getAllStudents = `-- name: GetAllStudents :many
SELECT id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name, slug, tg_chat_id
FROM users AS U
WHERE U.is_teacher = false
  AND U.is_superuser = false
ORDER BY U.id
`

func (q *Queries) GetAllStudents(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.IsTeacher,
			&i.IsSuperuser,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Slug,
			&i.TgChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
