// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teachers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeacher = `-- name: CreateTeacher :one
WITH new_user AS (
	INSERT INTO users (email, password, is_teacher, first_name, middle_name, last_name)
		VALUES ($1, $2, true, $3, $4, $5)
	RETURNING id, email, password, is_teacher, is_superuser, first_name, middle_name, last_name
)
INSERT INTO teachers (user_id)
	VALUES ((SELECT id FROM new_user))
RETURNING user_id
`

type CreateTeacherParams struct {
	Email      string
	Password   []byte
	FirstName  string
	MiddleName pgtype.Text
	LastName   string
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTeacher,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
	)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
