basePath: /api/v1
definitions:
  auth.UserCreate:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      middleName:
        type: string
      password:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  auth.UserGet:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      middleName:
        type: string
    type: object
  auth.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  courses.Category:
    properties:
      title:
        type: string
    type: object
  courses.Course:
    properties:
      description:
        type: string
      grade:
        type: integer
      price:
        type: integer
      title:
        type: string
    required:
    - grade
    - price
    - title
    type: object
  courses.CourseCreate:
    properties:
      categoryId:
        description: |-
          Title       string `json:"title" binding:"required"`
          Description string `json:"description" copier:"-"`
          Price       int32 `json:"price" binding:"required"`
          Year        int16 `json:"grade" binding:"required" copier:"-"`
        type: integer
      description:
        type: string
      grade:
        type: integer
      price:
        type: integer
      subjectId:
        type: integer
      title:
        type: string
    required:
    - categoryId
    - grade
    - price
    - subjectId
    - title
    type: object
  courses.CourseWithData:
    properties:
      category:
        $ref: '#/definitions/courses.Category'
      course:
        $ref: '#/definitions/courses.Course'
      subject:
        $ref: '#/definitions/courses.Subject'
    type: object
  courses.Subject:
    properties:
      title:
        type: string
    type: object
info:
  contact: {}
  description: Learn & Grow API
  title: My magical API
  version: "1"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.UserLogin'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/auth.UserGet'
      summary: Log in user, issue JWT into Cookie
      tags:
      - Auth
  /auth/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.UserGet'
      summary: Get current user data
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.UserGet'
      summary: Create user (only superuser)
      tags:
      - Auth
  /courses/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/courses.CourseWithData'
            type: array
      summary: Gets All courses
      tags:
      - Courses
    post:
      consumes:
      - application/json
      parameters:
      - description: Course
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/courses.CourseCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/courses.Course'
      summary: Create a course
      tags:
      - Courses
  /ping:
    get:
      description: |-
        In the realm of code where data flows,
        A whisper travels where the network goes.
        With a simple command, a heartbeat is sent,
        To check the connection, to see where it went.

        "Ping," it calls, like a friendly chime,
        A request for response, a dance through time.
        From client to server, a message takes flight,
        In packets it journeys, through day and through night.

        "Are you there?" it asks, with a digital sigh,
        A promise of data, a link to the sky.
        The echo returns, a confirmation so sweet,
        A symphony of bytes, where two systems meet.

        In the world of APIs, where services blend,
        Ping is the guardian, the reliable friend.
        It measures the distance, the latency's grace,
        A pulse of the network, a test of the space.

        So here’s to the ping, in its silent decree,
        A bridge in the ether, connecting you and me.
        With each little packet, a story unfolds,
        In the language of tech, where the future beholds.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping API
      tags:
      - base
  /teachers/:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.UserCreate'
      produces:
      - application/json
      responses: {}
      summary: Create teacher
      tags:
      - Teachers
swagger: "2.0"
